version: '3.8'
name: huntit-e2e-test

services:
  backend-database-e2e:
    image: postgres:16
    container_name: backend-database-e2e
    env_file:
      - .env.test
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5441:${DATABASE_PORT}
    volumes:
      - ../volumes/huntit/database-e2e-test:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} > /dev/null || exit 1']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - huntit_network_e2e_test

  api-service-e2e:
    container_name: api-service-e2e
    env_file:
      - .env.test
    environment:
      - FORCE_COLOR=1
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - NODE_VERSION=${NODE_VERSION}
    user: node
    working_dir: /srv
    volumes:
      - ./:/srv
    depends_on:
      - backend-database-e2e
      - jaeger-e2e
    ports:
      - 9229:9299
      - 3000:3000
    networks:
      - huntit_network_e2e_test
    mem_limit: 2048MB

  jaeger-e2e:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-e2e
    ports:
      - 16687:16686
      - 4317:4317
      - 4318:4318
    environment:
      - LOG_LEVEL=debug

networks:
  huntit_network_e2e_test:
    driver: bridge

volumes:
  dev-postgres-data:
    external: true
